# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/protogen/gcdm_server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from src.protogen import gcdm_netcdf_pb2 as src_dot_protogen_dot_gcdm__netcdf__pb2
from src.protogen import gcdm_grid_pb2 as src_dot_protogen_dot_gcdm__grid__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/protogen/gcdm_server.proto',
  package='ucar.gcdm',
  syntax='proto3',
  serialized_options=b'\n\tucar.gcdmB\017GcdmServerProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1esrc/protogen/gcdm_server.proto\x12\tucar.gcdm\x1a\x1esrc/protogen/gcdm_netcdf.proto\x1a\x1csrc/protogen/gcdm_grid.proto2\xb5\x02\n\x04Gcdm\x12H\n\x0fGetNetcdfHeader\x12\x18.ucar.gcdm.HeaderRequest\x1a\x19.ucar.gcdm.HeaderResponse\"\x00\x12\x44\n\rGetNetcdfData\x12\x16.ucar.gcdm.DataRequest\x1a\x17.ucar.gcdm.DataResponse\"\x00\x30\x01\x12Q\n\x0eGetGridDataset\x12\x1d.ucar.gcdm.GridDatasetRequest\x1a\x1e.ucar.gcdm.GridDatasetResponse\"\x00\x12J\n\x0bGetGridData\x12\x1a.ucar.gcdm.GridDataRequest\x1a\x1b.ucar.gcdm.GridDataResponse\"\x00\x30\x01\x42\x1c\n\tucar.gcdmB\x0fGcdmServerProtob\x06proto3'
  ,
  dependencies=[src_dot_protogen_dot_gcdm__netcdf__pb2.DESCRIPTOR,src_dot_protogen_dot_gcdm__grid__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_GCDM = _descriptor.ServiceDescriptor(
  name='Gcdm',
  full_name='ucar.gcdm.Gcdm',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=108,
  serialized_end=417,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetNetcdfHeader',
    full_name='ucar.gcdm.Gcdm.GetNetcdfHeader',
    index=0,
    containing_service=None,
    input_type=src_dot_protogen_dot_gcdm__netcdf__pb2._HEADERREQUEST,
    output_type=src_dot_protogen_dot_gcdm__netcdf__pb2._HEADERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetNetcdfData',
    full_name='ucar.gcdm.Gcdm.GetNetcdfData',
    index=1,
    containing_service=None,
    input_type=src_dot_protogen_dot_gcdm__netcdf__pb2._DATAREQUEST,
    output_type=src_dot_protogen_dot_gcdm__netcdf__pb2._DATARESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetGridDataset',
    full_name='ucar.gcdm.Gcdm.GetGridDataset',
    index=2,
    containing_service=None,
    input_type=src_dot_protogen_dot_gcdm__grid__pb2._GRIDDATASETREQUEST,
    output_type=src_dot_protogen_dot_gcdm__grid__pb2._GRIDDATASETRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetGridData',
    full_name='ucar.gcdm.Gcdm.GetGridData',
    index=3,
    containing_service=None,
    input_type=src_dot_protogen_dot_gcdm__grid__pb2._GRIDDATAREQUEST,
    output_type=src_dot_protogen_dot_gcdm__grid__pb2._GRIDDATARESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GCDM)

DESCRIPTOR.services_by_name['Gcdm'] = _GCDM

# @@protoc_insertion_point(module_scope)
