name: test_env
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - netcdf4=1.5.7
  - numpy=1.20.3
  - pytest=6.2.4
  - pytest-cov=2.12.1
  - coveralls=3.2.0
  - xarray=0.19.0
  - pip:
    - pygcdm>=0.0.6
    - grpcio==1.39.0
    - grpcio-tools==1.39.0
