name: pygcdm tests

on: [push]

jobs:
  RunTests:
    name: ${{ matrix.os }} ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        python-version: [3.9]
        os: [macos]

    steps:
    - name: Checkout source
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 100
          
    - name: Install miniconda and environment
      uses: conda-incubator/setup-miniconda@v2
      with:
          activate-environment: anaconda-client-env
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
      
    - name: Run tests
      run: |
        pytest test/unit_tests.py
        pytest test/functional_tests.py
