name: pygcdm tests

on: [push]

jobs:
  RunTests:
    name: ${{ matrix.os }} ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        python-version: [3.9]
        os: [macos]

    steps:
    - name: Checkout source
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 100
        
    - name: Setup conda caching
      uses: actions/cache@v2.1.6
      with:
        path: ~/conda_pkgs_dir
        key: conda-tests-${{ runner.os }}-${{ matrix.python-version}}-${{ hashFiles('ci/*') }}
        restore-keys: |
          conda-tests-${{ runner.os }}-${{ matrix.python-version}}
          conda-tests-${{ runner.os }}
          conda-tests-
          
    - name: Install miniconda 
      uses: conda-incubator/setup-miniconda@v2
      with:
          miniforge-version: latest
          environment-file: ci/environment.yml
          activate-environment: test-env
          python-version: ${{ matrix.python-version }}
          channels: anaconda, conda-forge, defaults
          use-only-tar-bz2: true

    - name: Install pygcdm locally
      run: |
        pip install .
      
    - name: Run tests
      run: |
        pytest --cov=. test/*
        
    - name: Upload coverage data
      run: |
        coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
