name: pygcdm tests

on: [push]

jobs:
  RunTests:
    name: ${{ matrix.os }} ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}-latests
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        python-version: [3.9]
        os: [macOS]

    steps:
    - name: Checkout source
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 100
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2.1.1
      with:
        miniforge-version: latest
        miniforge-variant: mambaforge
        python-version: ${{ matrix.python-version }}
        channel-priority: strict
        channels: conda-forge/label/testing,conda-forge
        show-channel-urls: true
        # Needed for caching
        use-only-tar-bz2: true
     
    - name: Install dependencies
      run: mamba install --quiet --yes --file environment.yml
      
    - name: Run tests
      run: |
        pytest test/unit_tests.py
        pytest test/functional_tests.py
